app:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation
    prefix:   /registration
app:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation
    prefix:   /registration




acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"