acme_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeDemoBundle:Default:index }
_mail:
    path:     /mail/{name}
    defaults: { _controller: AcmeDemoBundle:Default:mail }
_new_conference:
    path:     /new
    defaults: { _controller: AcmeDemoBundle:Conference:new}
    
_delete_conference:
    path:     /delete/{id}
    defaults: { _controller: AcmeDemoBundle:Conference:delete}
    
_sign_show:
    path:     /signshow
    defaults: { _controller: AcmeDemoBundle:SignUp:signShow}
  
    
_sign_up:
    path:     /signup/{id}
    defaults: { _controller: AcmeDemoBundle:SignUp:sign}