Acme\DemoBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:          
        gender:
            type: string
            
        company:
            type: string
            length: '100'  
           
        position:
            type: string
            length: '100'   
            
        address:
            type: string
            length: '100'   
            
        phone:
            type: string
            length: '20' 
        
    oneToMany:
        signUps:
            targetEntity: SignUp
            mappedBy: user
    